version: '3.8'
services:

    #Node Service
    iq_devs_frontend:
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: iq_devs_frontend
        container_name: iq_devs_frontend
        restart: unless-stopped
        tty: true
        env_file:
            - ../.env
        working_dir: /app
        ports:
            - "7100:80"
            - "7101:8081"
        volumes:
            - ../:/app
            - ./conf.d/:/etc/nginx/conf.d/
        networks:
            - iq_devs_frontend-network

#Docker Networks
networks:
    iq_devs_frontend-network:
        driver: bridge
